substitutions:
  ext_comp_repo_ref: develop
  ext_comp_repo_url: https://github.com/FutureProofHomes/Satellite1-ESPHome 

external_components:
  - source:
      type: git
      url: ${ext_comp_repo_url}
      ref: ${ext_comp_repo_ref}
    components:
        - audio 
        - fusb302b
        - i2s_audio
        - http_request
        - memory_flasher
        - micro_wake_word
        - mixer
        - pcm5122
        - resampler 
        - satellite1 
        - snapcast
        - speaker
        - tas2780

